#!/bin/sh

# PROGRAM INSTALLS
pgms=()
# backend
pgms+=("rofi")
pgms+=("compton")
pgms+=("feh")
pgms+=("redshift")
pgms+=("xorg-xbacklight")
pgms+=("xautolock")
pgms+=("pamixer")
pgms+=("playerctl")
pgms+=("nmcli")
pgms+=("conky")
pgms+=("i3lock-color")
pgms+=("sddm")
pgms+=("sddm-maia-theme")
pgms+=("papirus-maia-icon-theme")
pgms+=("ttf-emojione-color")
pgms+=("vimix-gtk-themes-git")
pgms+=("dunst")
pgms+=("mpc")
# utility
pgms+=("termite")
pgms+=("lxappearance")
pgms+=("ranger")
pgms+=("gparted")
pgms+=("neofetch")
pgms+=("pcloudcc")
pgms+=("pcloud-drive")
pgms+=("kdeconnectd")
pgms+=("openvpn")
pgms+=("calc")
pgms+=("ncmpcpp")
pgms+=("mpv")
pgms+=("odrive")
pgms+=("zathura-pdf-mupdf")
pgms+=("gotop")
pgms+=("vim-plug")
# applications
pgms+=("gimp")
pgms+=("transmission-remote-gtk")
pgms+=("transmission-cli")

exec yay -S ${pgms[*]}
