" Vim Config
"   Petra E Bauman <petra.e.bauman@gmail.com>
"   https://codeberg.org/petraglyph/dotfiles

filetype plugin on
set encoding=utf8
set clipboard+=unnamedplus


" Appearance
set number
set wrap lbr
set tabstop=4
set softtabstop=4
set shiftwidth=4
set listchars=tab:¦\ ,trail:~,extends:>,precedes:<
set list
set guicursor=
set scrolloff=5


" Keyboard Shortcuts
nnoremap <S-tab> :bprev<Enter>
nnoremap <tab>   :bnext<Enter>
" document navigation
noremap <silent> k gk
noremap <silent> j gj
noremap <silent> <S-h> g^
noremap <silent> <S-j> 8gj
noremap <silent> <S-k> 8gk
noremap <silent> <S-l> g$
nmap <S-u> :redo<Enter>
" editing
nmap <enter> o<esc>
nmap ; :
nmap < v<
nmap > v>


" Netrw
let g:netrw_banner = 1
let g:netrw_liststyle = 0
nmap <C-f> :Explore<Enter>

" Spellcheck
autocmd FileType markdown setlocal spell
autocmd FileType tex setlocal spell
autocmd FileType text setlocal spell


" Remember cursor position
augroup vimStartup
	autocmd!
	autocmd BufReadPost * if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
		\ | exe "normal! g`\""
	\ | endif
augroup END
