#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#while :
#do
#    load="$(cut -d ' ' -f1 /proc/loadavg)"
#    cpus="$(nproc)"
#    echo "$load"

    # color if load is too high
#    awk -v cpus=$cpus -v cpuload=$load
#    sleep .5
#done

load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

#let "loadperc = load*25.0"
loadperc=$(echo "$load * 25" | bc)

# full text
#echo "$loadperc "
printf -v loadperc "%02d" $loadperc
echo "${loadperc%.*}%  "

# short text
echo "$load "

# color if load is too high
if [ $loadperc = 100 ]; then
    echo "#cc0000"
elif [[ ${loadperc:0:1} = "9" ]]; then
    echo "#cc0000"
else
    echo "#eeeeee"
fi
